/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryManagementProject.views;

import LibraryManagementProject.controllers.MainController;
import LibraryManagementProject.factory.Book;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emmas
 */
public class CatalogViewStudent extends javax.swing.JFrame {
    private MainController mainController;
    /**
     * Creates new form CatalogView
     */
    public CatalogViewStudent(MainController mainController) {
        this.mainController = mainController;
        initComponents();
        displayBookCatalog();
    }
    
    private void displayBookCatalog() {
        DefaultTableModel tableModel = (DefaultTableModel) bookCatalogStudentTable.getModel();
        tableModel.setRowCount(0); 

        Map<String, Book> bookCatalogStudent = mainController.getBookCatalogStudent();
        for (Book book : bookCatalogStudent.values()) {
            tableModel.addRow(new Object[]{
                    book.getSN(),
                    book.getTitle(),
                    book.getAuthor(),
                    book.getPublisher(),
                    book.getPrice(),
                    book.getQte(),
                    book.getType()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        catalogLabel = new javax.swing.JLabel();
        borrowButton = new javax.swing.JButton();
        borrowBookTextField = new javax.swing.JTextField();
        bookIDLabel = new javax.swing.JLabel();
        searchBookLabel = new javax.swing.JLabel();
        authorRadioButton = new javax.swing.JRadioButton();
        publisherRadioButton = new javax.swing.JRadioButton();
        titleRadioButton = new javax.swing.JRadioButton();
        searchBookTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        studentIDLabel = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookCatalogStudentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(194, 228, 255));

        catalogLabel.setBackground(new java.awt.Color(27, 73, 101));
        catalogLabel.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        catalogLabel.setForeground(new java.awt.Color(27, 73, 101));
        catalogLabel.setText("Book Catalog");

        borrowButton.setBackground(new java.awt.Color(95, 168, 211));
        borrowButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        borrowButton.setForeground(new java.awt.Color(27, 73, 101));
        borrowButton.setText("Request Borrow");

        borrowBookTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        bookIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bookIDLabel.setForeground(new java.awt.Color(27, 73, 101));
        bookIDLabel.setText("Enter book id:");

        searchBookLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        searchBookLabel.setForeground(new java.awt.Color(27, 73, 101));
        searchBookLabel.setText("Search book by:");

        buttonGroup1.add(authorRadioButton);
        authorRadioButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        authorRadioButton.setForeground(new java.awt.Color(27, 73, 101));
        authorRadioButton.setText("AUTHOR");

        buttonGroup1.add(publisherRadioButton);
        publisherRadioButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        publisherRadioButton.setForeground(new java.awt.Color(27, 73, 101));
        publisherRadioButton.setText("PUBLISHER");

        buttonGroup1.add(titleRadioButton);
        titleRadioButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        titleRadioButton.setForeground(new java.awt.Color(27, 73, 101));
        titleRadioButton.setText("TITLE");

        searchBookTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        searchButton.setBackground(new java.awt.Color(95, 168, 211));
        searchButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(27, 73, 101));
        searchButton.setText("Search");

        backButton.setBackground(new java.awt.Color(95, 168, 211));
        backButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(27, 73, 101));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        studentIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        studentIDLabel.setForeground(new java.awt.Color(27, 73, 101));
        studentIDLabel.setText("Enter student id:");

        studentIdTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        studentIdTextField.setForeground(new java.awt.Color(27, 73, 101));

        bookCatalogStudentTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bookCatalogStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "Title", "Author", "Publisher", "Price", "Quantity", "Type"
            }
        ));
        bookCatalogStudentTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        bookCatalogStudentTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(bookCatalogStudentTable);
        bookCatalogStudentTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                    .addComponent(searchBookTextField))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bookIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(borrowBookTextField))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(studentIDLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(borrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(searchBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(titleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(authorRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(publisherRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(catalogLabel)))
                .addContainerGap(805, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(borrowBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookIDLabel))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIDLabel)
                            .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(borrowButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBookLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleRadioButton)
                    .addComponent(authorRadioButton)
                    .addComponent(publisherRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {borrowBookTextField, searchBookTextField, studentIdTextField});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainController mainController = new MainController();
                new CatalogViewStudent(mainController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton authorRadioButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable bookCatalogStudentTable;
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JTextField borrowBookTextField;
    private javax.swing.JButton borrowButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel catalogLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton publisherRadioButton;
    private javax.swing.JLabel searchBookLabel;
    private javax.swing.JTextField searchBookTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JRadioButton titleRadioButton;
    // End of variables declaration//GEN-END:variables
}
