/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryManagementProject.views;

import LibraryManagementProject.controllers.LibrarianController;

/**
 *
 * @author bridj
 */
public class LibrarianSignUpView extends javax.swing.JFrame {

    // private LibrarianController librarianController;
    /**
     * Creates new form LibrarianSignUpView
     */
//    public LibrarianSignUpView(LibrarianController librarianController) {
//        this.librarianController = librarianController;
//        initComponents();
//    }
    
    public LibrarianSignUpView() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelLibrarianID = new javax.swing.JLabel();
        labelLibrarianUsername = new javax.swing.JLabel();
        labelLibrarianPassword = new javax.swing.JLabel();
        txtfieldLibrarianID = new javax.swing.JTextField();
        txtfieldLibrarianUsername = new javax.swing.JTextField();
        txtfieldLibrarianPassword = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Librarian Sign Up");
        setBackground(new java.awt.Color(202, 233, 255));
        setMaximumSize(new java.awt.Dimension(500, 300));
        setName("librarianSignupFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        jPanel1.setBackground(new java.awt.Color(194, 228, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        labelTitle.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(27, 73, 101));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Librarian Sign Up");
        labelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(214, 237, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        labelLibrarianID.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        labelLibrarianID.setForeground(new java.awt.Color(27, 73, 101));
        labelLibrarianID.setText("Librarian ID:");

        labelLibrarianUsername.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        labelLibrarianUsername.setForeground(new java.awt.Color(27, 73, 101));
        labelLibrarianUsername.setText("Username:");

        labelLibrarianPassword.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        labelLibrarianPassword.setForeground(new java.awt.Color(27, 73, 101));
        labelLibrarianPassword.setText("Password:");

        txtfieldLibrarianID.setBackground(new java.awt.Color(214, 237, 255));
        txtfieldLibrarianID.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        txtfieldLibrarianID.setForeground(new java.awt.Color(27, 73, 101));

        txtfieldLibrarianUsername.setBackground(new java.awt.Color(214, 237, 255));
        txtfieldLibrarianUsername.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        txtfieldLibrarianUsername.setForeground(new java.awt.Color(27, 73, 101));

        txtfieldLibrarianPassword.setBackground(new java.awt.Color(214, 237, 255));
        txtfieldLibrarianPassword.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        txtfieldLibrarianPassword.setForeground(new java.awt.Color(27, 73, 101));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelLibrarianPassword)
                        .addGap(18, 18, 18)
                        .addComponent(txtfieldLibrarianPassword))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelLibrarianUsername)
                        .addGap(18, 18, 18)
                        .addComponent(txtfieldLibrarianUsername))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelLibrarianID)
                        .addGap(18, 18, 18)
                        .addComponent(txtfieldLibrarianID)))
                .addGap(15, 15, 15))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelLibrarianID, labelLibrarianPassword, labelLibrarianUsername});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLibrarianID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldLibrarianID))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLibrarianUsername)
                    .addComponent(txtfieldLibrarianUsername))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLibrarianPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldLibrarianPassword))
                .addGap(17, 17, 17))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelLibrarianID, labelLibrarianPassword, labelLibrarianUsername});

        btnSignup.setBackground(new java.awt.Color(95, 168, 211));
        btnSignup.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(27, 73, 101));
        btnSignup.setText("Sign Up");
        btnSignup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitle)
                    .addComponent(btnSignup))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSignup)
                .addGap(67, 67, 67))
        );

        labelTitle.getAccessibleContext().setAccessibleName("labelTitle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        /*
        Need to implement
        */

    }//GEN-LAST:event_btnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianSignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianSignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianSignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianSignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianSignUpView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelLibrarianID;
    private javax.swing.JLabel labelLibrarianPassword;
    private javax.swing.JLabel labelLibrarianUsername;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField txtfieldLibrarianID;
    private javax.swing.JTextField txtfieldLibrarianPassword;
    private javax.swing.JTextField txtfieldLibrarianUsername;
    // End of variables declaration//GEN-END:variables
}
