package LibraryManagementProject.views;

import LibraryManagementProject.controllers.MainController;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1982228, emmas
 */
public class LibrarianView extends javax.swing.JFrame {
    private MainController mainController;
    private ResourceBundle bundle;
    private ResourceBundle bundleFR;

    
    public LibrarianView(MainController mainController) {
        this.mainController = mainController;
        initComponents();
        currentDateTime();
        displayIssuedBooks();
        bundle = ResourceBundle.getBundle("LibrarianView");
        bundleFR = ResourceBundle.getBundle("LibrarianView_fr_FR", Locale.FRANCE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        booksBorrowedTextArea1 = new javax.swing.JTextArea();
        enterRequetsBookLabel1 = new javax.swing.JLabel();
        enterRequestBookTextField1 = new javax.swing.JTextField();
        booksRequestLabel1 = new javax.swing.JLabel();
        allowButton1 = new javax.swing.JButton();
        denyButton1 = new javax.swing.JButton();
        bookCatalogLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bookCatalogTextArea = new javax.swing.JTextArea();
        enterReturnLabel = new javax.swing.JLabel();
        enterRequestBookTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksBorrowedTextArea = new javax.swing.JTextArea();
        allowButton = new javax.swing.JButton();
        denyButton = new javax.swing.JButton();
        booksRequestLabel = new javax.swing.JLabel();
        enterRequetsBookLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        booksReturnedTextArea = new javax.swing.JTextArea();
        titleLable = new javax.swing.JLabel();
        catalogButton = new javax.swing.JButton();
        booksRequestLabel2 = new javax.swing.JLabel();
        issuedBookButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        enterReturnBookTextField = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        librarianTitleLabel = new javax.swing.JLabel();
        bookReturnsPanel = new javax.swing.JPanel();
        booksRequestLabel4 = new javax.swing.JLabel();
        returnBookButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        issuedBooksLibrarianTable = new javax.swing.JTable();
        sidePanel = new javax.swing.JPanel();
        dateTime = new javax.swing.JLabel();
        pictureLabel = new javax.swing.JLabel();
        sideActionPanel = new javax.swing.JPanel();
        addBookButton = new javax.swing.JButton();
        viewCatalogButton = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        frenchButton = new javax.swing.JRadioButton();
        englishButton = new javax.swing.JRadioButton();

        booksBorrowedTextArea1.setColumns(20);
        booksBorrowedTextArea1.setRows(5);
        jScrollPane2.setViewportView(booksBorrowedTextArea1);

        enterRequetsBookLabel1.setText("Enter request number:");

        booksRequestLabel1.setText("BOOK request");

        allowButton1.setText("Allow");

        denyButton1.setText("Deny");

        bookCatalogLabel.setText("BOOK CATALOG");

        bookCatalogTextArea.setColumns(20);
        bookCatalogTextArea.setRows(5);
        jScrollPane4.setViewportView(bookCatalogTextArea);

        enterReturnLabel.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        enterReturnLabel.setForeground(new java.awt.Color(27, 73, 101));
        enterReturnLabel.setText("Enter return number:");

        booksBorrowedTextArea.setColumns(20);
        booksBorrowedTextArea.setRows(5);
        jScrollPane1.setViewportView(booksBorrowedTextArea);

        allowButton.setBackground(new java.awt.Color(95, 168, 211));
        allowButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        allowButton.setForeground(new java.awt.Color(27, 73, 101));
        allowButton.setText("Allow");

        denyButton.setBackground(new java.awt.Color(95, 168, 211));
        denyButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        denyButton.setForeground(new java.awt.Color(27, 73, 101));
        denyButton.setText("Deny");

        booksRequestLabel.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        booksRequestLabel.setForeground(new java.awt.Color(27, 73, 101));
        booksRequestLabel.setText("BOOK REQUEST");

        enterRequetsBookLabel.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        enterRequetsBookLabel.setForeground(new java.awt.Color(27, 73, 101));
        enterRequetsBookLabel.setText("Enter request number:");

        booksReturnedTextArea.setColumns(20);
        booksReturnedTextArea.setRows(5);
        jScrollPane3.setViewportView(booksReturnedTextArea);

        titleLable.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        titleLable.setForeground(new java.awt.Color(27, 73, 101));
        titleLable.setText("Library summary");

        catalogButton.setBackground(new java.awt.Color(95, 168, 211));
        catalogButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        catalogButton.setForeground(new java.awt.Color(27, 73, 101));
        catalogButton.setText("Catalog");

        booksRequestLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        booksRequestLabel2.setForeground(new java.awt.Color(27, 73, 101));
        booksRequestLabel2.setText("BOOK RETURNS");

        issuedBookButton.setBackground(new java.awt.Color(95, 168, 211));
        issuedBookButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        issuedBookButton.setForeground(new java.awt.Color(27, 73, 101));
        issuedBookButton.setText("Issued Books");

        addButton.setBackground(new java.awt.Color(95, 168, 211));
        addButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(27, 73, 101));
        addButton.setText("Add a book");

        returnButton.setBackground(new java.awt.Color(95, 168, 211));
        returnButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        returnButton.setForeground(new java.awt.Color(27, 73, 101));
        returnButton.setText("Return");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(202, 233, 255));
        setName("librarianView"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        mainPanel.setBackground(new java.awt.Color(202, 233, 255));
        mainPanel.setForeground(new java.awt.Color(202, 233, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        librarianTitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        librarianTitleLabel.setForeground(new java.awt.Color(27, 73, 101));
        librarianTitleLabel.setText("Librarian Dashboard");

        bookReturnsPanel.setBackground(new java.awt.Color(214, 237, 255));
        bookReturnsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        booksRequestLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        booksRequestLabel4.setForeground(new java.awt.Color(27, 73, 101));
        booksRequestLabel4.setText("BOOK ISSUED");

        returnBookButton.setBackground(new java.awt.Color(95, 168, 211));
        returnBookButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        returnBookButton.setForeground(new java.awt.Color(27, 73, 101));
        returnBookButton.setText("Return Book");
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        issuedBooksLibrarianTable.setBackground(new java.awt.Color(194, 228, 255));
        issuedBooksLibrarianTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        issuedBooksLibrarianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "SN", "Title", "Student ID", "Quantity", "Issued Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(issuedBooksLibrarianTable);
        if (issuedBooksLibrarianTable.getColumnModel().getColumnCount() > 0) {
            issuedBooksLibrarianTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            issuedBooksLibrarianTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            issuedBooksLibrarianTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            issuedBooksLibrarianTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            issuedBooksLibrarianTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            issuedBooksLibrarianTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        javax.swing.GroupLayout bookReturnsPanelLayout = new javax.swing.GroupLayout(bookReturnsPanel);
        bookReturnsPanel.setLayout(bookReturnsPanelLayout);
        bookReturnsPanelLayout.setHorizontalGroup(
            bookReturnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookReturnsPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(bookReturnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookReturnsPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookReturnsPanelLayout.createSequentialGroup()
                        .addComponent(booksRequestLabel4)
                        .addGap(272, 272, 272))))
            .addGroup(bookReturnsPanelLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(returnBookButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bookReturnsPanelLayout.setVerticalGroup(
            bookReturnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookReturnsPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(booksRequestLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnBookButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bookReturnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(librarianTitleLabel)
                .addGap(193, 193, 193))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(librarianTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookReturnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        sidePanel.setBackground(new java.awt.Color(173, 221, 255));
        sidePanel.setInheritsPopupMenu(true);
        sidePanel.setPreferredSize(new java.awt.Dimension(275, 600));

        dateTime.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        dateTime.setForeground(new java.awt.Color(43, 116, 161));
        dateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTime.setText("jLabel1");
        dateTime.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        dateTime.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 73, 101)));
        dateTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dateTime.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/illustrations/resized-images (3)/libraryDesign5.png"))); // NOI18N
        pictureLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        sideActionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(27, 73, 101))); // NOI18N
        sideActionPanel.setName(""); // NOI18N
        sideActionPanel.setOpaque(false);

        addBookButton.setBackground(new java.awt.Color(95, 168, 211));
        addBookButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addBookButton.setForeground(new java.awt.Color(27, 73, 101));
        addBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addBook.png"))); // NOI18N
        addBookButton.setText("Add A Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        viewCatalogButton.setBackground(new java.awt.Color(95, 168, 211));
        viewCatalogButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        viewCatalogButton.setForeground(new java.awt.Color(27, 73, 101));
        viewCatalogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shelfBook3.png"))); // NOI18N
        viewCatalogButton.setText("View Catalog");
        viewCatalogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCatalogButtonActionPerformed(evt);
            }
        });

        addStudentButton.setBackground(new java.awt.Color(95, 168, 211));
        addStudentButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(27, 73, 101));
        addStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addstudent.png"))); // NOI18N
        addStudentButton.setText("Add A Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideActionPanelLayout = new javax.swing.GroupLayout(sideActionPanel);
        sideActionPanel.setLayout(sideActionPanelLayout);
        sideActionPanelLayout.setHorizontalGroup(
            sideActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewCatalogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideActionPanelLayout.setVerticalGroup(
            sideActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(viewCatalogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        logOutButton.setBackground(new java.awt.Color(95, 168, 211));
        logOutButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(27, 73, 101));
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(frenchButton);
        frenchButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        frenchButton.setForeground(new java.awt.Color(27, 73, 101));
        frenchButton.setText("French");
        frenchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(englishButton);
        englishButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        englishButton.setForeground(new java.awt.Color(27, 73, 101));
        englishButton.setSelected(true);
        englishButton.setText("English");
        englishButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        englishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(985, 985, 985))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(englishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frenchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(sideActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(pictureLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(967, 967, 967))))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dateTime)
                .addGap(36, 36, 36)
                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(sideActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutButton)
                .addGap(55, 55, 55)
                .addComponent(englishButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frenchButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        sidePanel.getAccessibleContext().setAccessibleParent(mainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Add a student
    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        LibrarianAddStudentView addAStudentView = new LibrarianAddStudentView(mainController);
        addAStudentView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addStudentButtonActionPerformed
    // Log out
    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        mainController.getLibrarianController().logOut();
        EntryView entryView = new EntryView(mainController);
        entryView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed
    // Add book
    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        LibrarianAddBookView addBookView = new LibrarianAddBookView(mainController);
        addBookView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addBookButtonActionPerformed
    // View catalog
    private void viewCatalogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCatalogButtonActionPerformed
        LibrarianBookCatalogView view = new LibrarianBookCatalogView(mainController);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewCatalogButtonActionPerformed

    /**
     * Event handling: the librarian selects a specific row in order to return a book.
     * @param evt 
     */
    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        int selectedRow = issuedBooksLibrarianTable.getSelectedRow();
        // If librarian does not select a row, error message will pop up to select.
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Please select a book to return.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // the row in which the librarian clicks will take the issue id and it will return the books with the issue id. (will make the books available).
        int issuedBookId = (int) issuedBooksLibrarianTable.getValueAt(selectedRow, 0);
        boolean success = mainController.returnBookLibrarian(issuedBookId);
        if (success) {
            JOptionPane.showMessageDialog(this, "Book returned successfully.");
            displayIssuedBooks();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to return book.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_returnBookButtonActionPerformed

    // Internationalization
    private void englishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishButtonActionPerformed
        librarianTitleLabel.setText(bundle.getString("Title"));
        booksRequestLabel4.setText(bundle.getString("BookIssued"));
        returnBookButton.setText(bundle.getString("Return"));
        logOutButton.setText(bundle.getString("LogOut"));
        viewCatalogButton.setText(bundle.getString("AddBook"));
        addBookButton.setText(bundle.getString("View"));
        addStudentButton.setText(bundle.getString("AddStu"));
    }//GEN-LAST:event_englishButtonActionPerformed

    private void frenchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchButtonActionPerformed
        librarianTitleLabel.setText(bundleFR.getString("Title"));
        booksRequestLabel4.setText(bundleFR.getString("BookIssued"));
        returnBookButton.setText(bundleFR.getString("Return"));
        logOutButton.setText(bundleFR.getString("LogOut"));
        viewCatalogButton.setText(bundleFR.getString("AddBook"));
        addBookButton.setText(bundleFR.getString("View"));
        addStudentButton.setText(bundleFR.getString("AddStu"));
    }//GEN-LAST:event_frenchButtonActionPerformed
    
    // Date and time labels
    public void currentDateTime() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("YYYY/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        dateTime.setText(dtf.format(now));
    }
    
    /**
     * The librarian issued books table are the list of issued books where
     * the librarian can see the id, sn, title, stid, quantity and the date that it has been issued.
     */
    private void displayIssuedBooks() {
        DefaultTableModel tableModel = (DefaultTableModel) issuedBooksLibrarianTable.getModel();
        tableModel.setRowCount(0);

        List<Map<String, Object>> issuedBooks = mainController.getIssuedIssuedBooksForLibrarian();
        for (Map<String, Object> issuedBook : issuedBooks) {
            tableModel.addRow(new Object[]{
                issuedBook.get("id"),
                issuedBook.get("SN"),
                issuedBook.get("title"),
                issuedBook.get("StId"),
                issuedBook.get("quantity"),
                issuedBook.get("IssueDate")
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainController mainController = new MainController();
                new LibrarianView(mainController).setVisible(true);
            }
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton allowButton;
    private javax.swing.JButton allowButton1;
    private javax.swing.JLabel bookCatalogLabel;
    private javax.swing.JTextArea bookCatalogTextArea;
    private javax.swing.JPanel bookReturnsPanel;
    private javax.swing.JTextArea booksBorrowedTextArea;
    private javax.swing.JTextArea booksBorrowedTextArea1;
    private javax.swing.JLabel booksRequestLabel;
    private javax.swing.JLabel booksRequestLabel1;
    private javax.swing.JLabel booksRequestLabel2;
    private javax.swing.JLabel booksRequestLabel4;
    private javax.swing.JTextArea booksReturnedTextArea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton catalogButton;
    private javax.swing.JLabel dateTime;
    private javax.swing.JButton denyButton;
    private javax.swing.JButton denyButton1;
    private javax.swing.JRadioButton englishButton;
    private javax.swing.JTextField enterRequestBookTextField;
    private javax.swing.JTextField enterRequestBookTextField1;
    private javax.swing.JLabel enterRequetsBookLabel;
    private javax.swing.JLabel enterRequetsBookLabel1;
    private javax.swing.JTextField enterReturnBookTextField;
    private javax.swing.JLabel enterReturnLabel;
    private javax.swing.JRadioButton frenchButton;
    private javax.swing.JButton issuedBookButton;
    private javax.swing.JTable issuedBooksLibrarianTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel librarianTitleLabel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel sideActionPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel titleLable;
    private javax.swing.JButton viewCatalogButton;
    // End of variables declaration//GEN-END:variables
}
