/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryManagementProject.views;

import LibraryManagementProject.controllers.LibrarianController;
import LibraryManagementProject.models.Librarian;

/**
 *
 * @author emmas
 */
public class LibrarianView extends javax.swing.JFrame {
    private LibrarianController librarianController;

    /**
     * Creates new form LibrarianView
     */
    public LibrarianView(LibrarianController librarianController) {
        this.librarianController = librarianController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        booksBorrowedTextArea1 = new javax.swing.JTextArea();
        enterRequetsBookLabel1 = new javax.swing.JLabel();
        enterRequestBookTextField1 = new javax.swing.JTextField();
        booksRequestLabel1 = new javax.swing.JLabel();
        allowButton1 = new javax.swing.JButton();
        denyButton1 = new javax.swing.JButton();
        bookCatalogLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bookCatalogTextArea = new javax.swing.JTextArea();
        enterReturnLabel = new javax.swing.JLabel();
        enterRequestBookTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksBorrowedTextArea = new javax.swing.JTextArea();
        allowButton = new javax.swing.JButton();
        denyButton = new javax.swing.JButton();
        booksRequestLabel = new javax.swing.JLabel();
        enterRequetsBookLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        booksReturnedTextArea = new javax.swing.JTextArea();
        titleLable = new javax.swing.JLabel();
        catalogButton = new javax.swing.JButton();
        booksRequestLabel2 = new javax.swing.JLabel();
        issuedBookButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        enterReturnBookTextField = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        framePanel = new javax.swing.JPanel();
        enterReturnLabel1 = new javax.swing.JLabel();
        enterRequestBookTextField2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        bookRequestsTextArea = new javax.swing.JTextArea();
        allowButton2 = new javax.swing.JButton();
        denyButton2 = new javax.swing.JButton();
        booksRequestLabel3 = new javax.swing.JLabel();
        enterRequetsBookLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        bookReturnTextArea = new javax.swing.JTextArea();
        titleLable1 = new javax.swing.JLabel();
        booksRequestLabel4 = new javax.swing.JLabel();
        enterReturnBookTextField1 = new javax.swing.JTextField();
        returnButton1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        actionsButtonPanel = new javax.swing.JPanel();
        addBookButton = new javax.swing.JButton();
        viewCatalogButton = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        issuedBooksButton = new javax.swing.JButton();

        booksBorrowedTextArea1.setColumns(20);
        booksBorrowedTextArea1.setRows(5);
        jScrollPane2.setViewportView(booksBorrowedTextArea1);

        enterRequetsBookLabel1.setText("Enter request number:");

        booksRequestLabel1.setText("BOOK request");

        allowButton1.setText("Allow");

        denyButton1.setText("Deny");

        bookCatalogLabel.setText("BOOK CATALOG");

        bookCatalogTextArea.setColumns(20);
        bookCatalogTextArea.setRows(5);
        jScrollPane4.setViewportView(bookCatalogTextArea);

        enterReturnLabel.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        enterReturnLabel.setForeground(new java.awt.Color(27, 73, 101));
        enterReturnLabel.setText("Enter return number:");

        booksBorrowedTextArea.setColumns(20);
        booksBorrowedTextArea.setRows(5);
        jScrollPane1.setViewportView(booksBorrowedTextArea);

        allowButton.setBackground(new java.awt.Color(95, 168, 211));
        allowButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        allowButton.setForeground(new java.awt.Color(27, 73, 101));
        allowButton.setText("Allow");

        denyButton.setBackground(new java.awt.Color(95, 168, 211));
        denyButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        denyButton.setForeground(new java.awt.Color(27, 73, 101));
        denyButton.setText("Deny");

        booksRequestLabel.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        booksRequestLabel.setForeground(new java.awt.Color(27, 73, 101));
        booksRequestLabel.setText("BOOK REQUEST");

        enterRequetsBookLabel.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        enterRequetsBookLabel.setForeground(new java.awt.Color(27, 73, 101));
        enterRequetsBookLabel.setText("Enter request number:");

        booksReturnedTextArea.setColumns(20);
        booksReturnedTextArea.setRows(5);
        jScrollPane3.setViewportView(booksReturnedTextArea);

        titleLable.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        titleLable.setForeground(new java.awt.Color(27, 73, 101));
        titleLable.setText("Library summary");

        catalogButton.setBackground(new java.awt.Color(95, 168, 211));
        catalogButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        catalogButton.setForeground(new java.awt.Color(27, 73, 101));
        catalogButton.setText("Catalog");

        booksRequestLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        booksRequestLabel2.setForeground(new java.awt.Color(27, 73, 101));
        booksRequestLabel2.setText("BOOK RETURNS");

        issuedBookButton.setBackground(new java.awt.Color(95, 168, 211));
        issuedBookButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        issuedBookButton.setForeground(new java.awt.Color(27, 73, 101));
        issuedBookButton.setText("Issued Books");

        addButton.setBackground(new java.awt.Color(95, 168, 211));
        addButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(27, 73, 101));
        addButton.setText("Add a book");

        returnButton.setBackground(new java.awt.Color(95, 168, 211));
        returnButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        returnButton.setForeground(new java.awt.Color(27, 73, 101));
        returnButton.setText("Return");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(202, 233, 255));
        setName("librarianView"); // NOI18N

        framePanel.setBackground(new java.awt.Color(202, 233, 255));
        framePanel.setForeground(new java.awt.Color(202, 233, 255));

        enterReturnLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        enterReturnLabel1.setForeground(new java.awt.Color(27, 73, 101));
        enterReturnLabel1.setText("Enter return number:");

        enterRequestBookTextField2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        bookRequestsTextArea.setColumns(20);
        bookRequestsTextArea.setRows(5);
        jScrollPane5.setViewportView(bookRequestsTextArea);

        allowButton2.setBackground(new java.awt.Color(95, 168, 211));
        allowButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        allowButton2.setForeground(new java.awt.Color(27, 73, 101));
        allowButton2.setText("Allow");

        denyButton2.setBackground(new java.awt.Color(95, 168, 211));
        denyButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        denyButton2.setForeground(new java.awt.Color(27, 73, 101));
        denyButton2.setText("Deny");

        booksRequestLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        booksRequestLabel3.setForeground(new java.awt.Color(27, 73, 101));
        booksRequestLabel3.setText("BOOK REQUEST");

        enterRequetsBookLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        enterRequetsBookLabel2.setForeground(new java.awt.Color(27, 73, 101));
        enterRequetsBookLabel2.setText("Enter request number:");

        bookReturnTextArea.setColumns(20);
        bookReturnTextArea.setRows(5);
        jScrollPane6.setViewportView(bookReturnTextArea);

        titleLable1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        titleLable1.setForeground(new java.awt.Color(27, 73, 101));
        titleLable1.setText("Librarian");

        booksRequestLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        booksRequestLabel4.setForeground(new java.awt.Color(27, 73, 101));
        booksRequestLabel4.setText("BOOK RETURNS");

        enterReturnBookTextField1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        returnButton1.setBackground(new java.awt.Color(95, 168, 211));
        returnButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        returnButton1.setForeground(new java.awt.Color(27, 73, 101));
        returnButton1.setText("Return");

        backBtn.setBackground(new java.awt.Color(95, 168, 211));
        backBtn.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(27, 73, 101));
        backBtn.setText("Back");

        actionsButtonPanel.setBackground(new java.awt.Color(202, 233, 255));
        actionsButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(27, 73, 101))); // NOI18N
        actionsButtonPanel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        addBookButton.setBackground(new java.awt.Color(95, 168, 211));
        addBookButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addBookButton.setForeground(new java.awt.Color(27, 73, 101));
        addBookButton.setText("Add a book");

        viewCatalogButton.setBackground(new java.awt.Color(95, 168, 211));
        viewCatalogButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        viewCatalogButton.setForeground(new java.awt.Color(27, 73, 101));
        viewCatalogButton.setText("Catalog");

        addStudentButton.setBackground(new java.awt.Color(95, 168, 211));
        addStudentButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(27, 73, 101));
        addStudentButton.setText("Add A Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        issuedBooksButton.setBackground(new java.awt.Color(95, 168, 211));
        issuedBooksButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        issuedBooksButton.setForeground(new java.awt.Color(27, 73, 101));
        issuedBooksButton.setText("Issued Books");

        javax.swing.GroupLayout actionsButtonPanelLayout = new javax.swing.GroupLayout(actionsButtonPanel);
        actionsButtonPanel.setLayout(actionsButtonPanelLayout);
        actionsButtonPanelLayout.setHorizontalGroup(
            actionsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(actionsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCatalogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actionsButtonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBookButton, addStudentButton, issuedBooksButton, viewCatalogButton});

        actionsButtonPanelLayout.setVerticalGroup(
            actionsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsButtonPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(actionsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookButton)
                    .addComponent(addStudentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(actionsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCatalogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedBooksButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        actionsButtonPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addBookButton, addStudentButton, issuedBooksButton, viewCatalogButton});

        javax.swing.GroupLayout framePanelLayout = new javax.swing.GroupLayout(framePanel);
        framePanel.setLayout(framePanelLayout);
        framePanelLayout.setHorizontalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePanelLayout.createSequentialGroup()
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framePanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(titleLable1))
                    .addGroup(framePanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(backBtn))
                    .addGroup(framePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(framePanelLayout.createSequentialGroup()
                                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(framePanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(booksRequestLabel4))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(returnButton1)
                                    .addComponent(enterReturnLabel1)
                                    .addComponent(enterReturnBookTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(actionsButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(framePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(framePanelLayout.createSequentialGroup()
                                        .addComponent(allowButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(denyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(enterRequestBookTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterRequetsBookLabel2)))
                            .addComponent(booksRequestLabel3))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        framePanelLayout.setVerticalGroup(
            framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLable1)
                .addGap(42, 42, 42)
                .addComponent(booksRequestLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(framePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(booksRequestLabel3)
                        .addGap(6, 6, 6))
                    .addGroup(framePanelLayout.createSequentialGroup()
                        .addComponent(enterReturnLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterReturnBookTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnButton1)
                        .addGap(43, 43, 43)))
                .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framePanelLayout.createSequentialGroup()
                        .addComponent(enterRequetsBookLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterRequestBookTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(framePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allowButton2)
                            .addComponent(denyButton2)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actionsButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(framePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        AddAStudentView addAStudentView = new AddAStudentView(librarianController);
        addAStudentView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LibrarianView(librarian).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsButtonPanel;
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton allowButton;
    private javax.swing.JButton allowButton1;
    private javax.swing.JButton allowButton2;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bookCatalogLabel;
    private javax.swing.JTextArea bookCatalogTextArea;
    private javax.swing.JTextArea bookRequestsTextArea;
    private javax.swing.JTextArea bookReturnTextArea;
    private javax.swing.JTextArea booksBorrowedTextArea;
    private javax.swing.JTextArea booksBorrowedTextArea1;
    private javax.swing.JLabel booksRequestLabel;
    private javax.swing.JLabel booksRequestLabel1;
    private javax.swing.JLabel booksRequestLabel2;
    private javax.swing.JLabel booksRequestLabel3;
    private javax.swing.JLabel booksRequestLabel4;
    private javax.swing.JTextArea booksReturnedTextArea;
    private javax.swing.JButton catalogButton;
    private javax.swing.JButton denyButton;
    private javax.swing.JButton denyButton1;
    private javax.swing.JButton denyButton2;
    private javax.swing.JTextField enterRequestBookTextField;
    private javax.swing.JTextField enterRequestBookTextField1;
    private javax.swing.JTextField enterRequestBookTextField2;
    private javax.swing.JLabel enterRequetsBookLabel;
    private javax.swing.JLabel enterRequetsBookLabel1;
    private javax.swing.JLabel enterRequetsBookLabel2;
    private javax.swing.JTextField enterReturnBookTextField;
    private javax.swing.JTextField enterReturnBookTextField1;
    private javax.swing.JLabel enterReturnLabel;
    private javax.swing.JLabel enterReturnLabel1;
    private javax.swing.JPanel framePanel;
    private javax.swing.JButton issuedBookButton;
    private javax.swing.JButton issuedBooksButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton returnButton1;
    private javax.swing.JLabel titleLable;
    private javax.swing.JLabel titleLable1;
    private javax.swing.JButton viewCatalogButton;
    // End of variables declaration//GEN-END:variables
}
