/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryManagementProject.views;

import LibraryManagementProject.controllers.MainController;

/**
 *
 * @author bridj
 */
public class StudentBorrowBookView extends javax.swing.JFrame {
    private MainController mainController;
    /**
     * Creates new form BorrowBook
     */
    public StudentBorrowBookView(MainController mainController) {
        this.mainController = mainController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        borrowBookTitleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookCatalogStudentTable = new javax.swing.JTable();
        borrowBookPanel = new javax.swing.JPanel();
        bookIDLabel = new javax.swing.JLabel();
        studentIDLabel = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        borrowBookTextField = new javax.swing.JTextField();
        bookQuantityTextField = new javax.swing.JTextField();
        borrowButton = new javax.swing.JButton();
        bookQuantityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(202, 233, 255));
        setSize(new java.awt.Dimension(622, 675));

        mainPanel.setBackground(new java.awt.Color(202, 233, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        borrowBookTitleLabel.setBackground(new java.awt.Color(27, 73, 101));
        borrowBookTitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        borrowBookTitleLabel.setForeground(new java.awt.Color(27, 73, 101));
        borrowBookTitleLabel.setText("Borrow Book");

        backButton.setBackground(new java.awt.Color(95, 168, 211));
        backButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(27, 73, 101));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        bookCatalogStudentTable.setBackground(new java.awt.Color(214, 237, 255));
        bookCatalogStudentTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bookCatalogStudentTable.setForeground(new java.awt.Color(27, 73, 101));
        bookCatalogStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "Title", "Author", "Publisher", "Price", "Quantity", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookCatalogStudentTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        bookCatalogStudentTable.setColumnSelectionAllowed(true);
        bookCatalogStudentTable.setGridColor(new java.awt.Color(27, 73, 101));
        bookCatalogStudentTable.setIntercellSpacing(new java.awt.Dimension(20, 20));
        bookCatalogStudentTable.setShowGrid(true);
        bookCatalogStudentTable.setShowHorizontalLines(true);
        bookCatalogStudentTable.setShowVerticalLines(true);
        jScrollPane2.setViewportView(bookCatalogStudentTable);
        bookCatalogStudentTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (bookCatalogStudentTable.getColumnModel().getColumnCount() > 0) {
            bookCatalogStudentTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            bookCatalogStudentTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            bookCatalogStudentTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            bookCatalogStudentTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            bookCatalogStudentTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            bookCatalogStudentTable.getColumnModel().getColumn(5).setPreferredWidth(100);
            bookCatalogStudentTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        borrowBookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrow Books", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(21, 57, 81))); // NOI18N
        borrowBookPanel.setOpaque(false);

        bookIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bookIDLabel.setForeground(new java.awt.Color(27, 73, 101));
        bookIDLabel.setText("Enter book id:");

        studentIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        studentIDLabel.setForeground(new java.awt.Color(27, 73, 101));
        studentIDLabel.setText("Enter student id:");

        studentIdTextField.setBackground(new java.awt.Color(235, 246, 255));
        studentIdTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        studentIdTextField.setForeground(new java.awt.Color(27, 73, 101));
        studentIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        borrowBookTextField.setBackground(new java.awt.Color(235, 246, 255));
        borrowBookTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        borrowBookTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bookQuantityTextField.setBackground(new java.awt.Color(235, 246, 255));
        bookQuantityTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bookQuantityTextField.setForeground(new java.awt.Color(27, 73, 101));
        bookQuantityTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        borrowButton.setBackground(new java.awt.Color(95, 168, 211));
        borrowButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        borrowButton.setForeground(new java.awt.Color(27, 73, 101));
        borrowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book4.png"))); // NOI18N
        borrowButton.setText("Request Borrow");

        bookQuantityLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bookQuantityLabel.setForeground(new java.awt.Color(27, 73, 101));
        bookQuantityLabel.setText("Enter book quantity:");

        javax.swing.GroupLayout borrowBookPanelLayout = new javax.swing.GroupLayout(borrowBookPanel);
        borrowBookPanel.setLayout(borrowBookPanelLayout);
        borrowBookPanelLayout.setHorizontalGroup(
            borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrowBookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(borrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(borrowBookPanelLayout.createSequentialGroup()
                        .addGroup(borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIDLabel)
                            .addComponent(bookQuantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(borrowBookTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(bookQuantityTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentIdTextField))))
                .addContainerGap())
        );
        borrowBookPanelLayout.setVerticalGroup(
            borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowBookPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowBookPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(bookQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borrowBookPanelLayout.createSequentialGroup()
                        .addGroup(borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIDLabel)
                            .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(borrowBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookIDLabel)
                            .addComponent(borrowBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bookQuantityLabel)))
                .addGap(18, 18, 18)
                .addComponent(borrowButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(borrowBookTitleLabel)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .addComponent(borrowBookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(backButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(borrowBookTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrowBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(backButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainController mainController = new MainController();
        StudentView studentView = new StudentView(mainController);
        studentView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentBorrowBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentBorrowBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentBorrowBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentBorrowBookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainController mainController = new MainController();
                new StudentBorrowBookView(mainController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable bookCatalogStudentTable;
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JLabel bookQuantityLabel;
    private javax.swing.JTextField bookQuantityTextField;
    private javax.swing.JPanel borrowBookPanel;
    private javax.swing.JTextField borrowBookTextField;
    private javax.swing.JLabel borrowBookTitleLabel;
    private javax.swing.JButton borrowButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIdTextField;
    // End of variables declaration//GEN-END:variables
}
