package LibraryManagementProject.views;

import LibraryManagementProject.controllers.MainController;
import LibraryManagementProject.controllers.StudentController;
import LibraryManagementProject.factory.Book;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1982228,emmas
 */
public class StudentBookCatalogView extends javax.swing.JFrame {

    private MainController mainController;

    public StudentBookCatalogView(MainController mainController) {
        this.mainController = mainController;
        initComponents();
        displayStudentBookCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        catalogViewTitleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        bookCatalogTableScrollPane = new javax.swing.JScrollPane();
        studentBookCatalogTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Catalog ");
        setSize(new java.awt.Dimension(1136, 600));

        mainPanel.setBackground(new java.awt.Color(202, 233, 255));

        catalogViewTitleLabel.setBackground(new java.awt.Color(27, 73, 101));
        catalogViewTitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        catalogViewTitleLabel.setForeground(new java.awt.Color(27, 73, 101));
        catalogViewTitleLabel.setText("Book Catalog");

        backButton.setBackground(new java.awt.Color(95, 168, 211));
        backButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(27, 73, 101));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        studentBookCatalogTable.setBackground(new java.awt.Color(214, 237, 255));
        studentBookCatalogTable.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        studentBookCatalogTable.setForeground(new java.awt.Color(27, 73, 101));
        studentBookCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "Title", "Author", "Publisher", "Price", "Quantity", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentBookCatalogTable.setToolTipText("The student book catalog of all available books for students");
        studentBookCatalogTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        studentBookCatalogTable.setGridColor(new java.awt.Color(27, 73, 101));
        studentBookCatalogTable.setRowHeight(30);
        studentBookCatalogTable.setShowGrid(true);
        studentBookCatalogTable.getTableHeader().setReorderingAllowed(false);
        bookCatalogTableScrollPane.setViewportView(studentBookCatalogTable);
        if (studentBookCatalogTable.getColumnModel().getColumnCount() > 0) {
            studentBookCatalogTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            studentBookCatalogTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            studentBookCatalogTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            studentBookCatalogTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            studentBookCatalogTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            studentBookCatalogTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            studentBookCatalogTable.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(catalogViewTitleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(bookCatalogTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(backButton)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(catalogViewTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookCatalogTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        StudentView studentView = new StudentView(mainController);
        studentView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void displayStudentBookCatalog() {
        DefaultTableModel tableModel = (DefaultTableModel) studentBookCatalogTable.getModel();
        tableModel.setRowCount(0);

        Map<String, Book> bookCatalogStudent = mainController.getAvailableBooks();
        for (Book book : bookCatalogStudent.values()) {
            tableModel.addRow(new Object[]{
                book.getSN(),
                book.getTitle(),
                book.getAuthor(),
                book.getPublisher(),
                book.getPrice(),
                book.getQte(), 
                book.getType()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentBookCatalogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentBookCatalogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentBookCatalogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentBookCatalogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainController mainController = new MainController();
                new StudentBookCatalogView(mainController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane bookCatalogTableScrollPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel catalogViewTitleLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable studentBookCatalogTable;
    // End of variables declaration//GEN-END:variables
}
