/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LibraryManagementProject;

import LibraryManagementProject.controllers.LibrarianController;
import LibraryManagementProject.controllers.MainController;
import LibraryManagementProject.views.EntryView;
import LibraryManagementProject.views.LibrarianLoginView;
import LibraryManagementProject.views.LibrarianSignUpView;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class App {

    public static void main(String[] args) {
        DatabaseInitializer.getInstance();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainController mainController = MainController.getInstance();
                new EntryView(mainController).setVisible(true);
            }
        });
    }
}
