/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LibraryManagementProject;

    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.sql.Statement;

public class App {
   

    public static void main(String[] args) {
    }
}
/*

Testing 2

*/
/*

HEY EM! THIS IS A TEST TO SHOW HOW TO CREATE AND MERGE TO MAIN BRANCH

*/
/*


    String title = The alchemist
    String sql = "SELECT TITLE from library where name== title"
    Book currentBook = statement.executeUpdate(sql);
    
*/